### PR TITLE
Restore Java 8 runtime compatibility

### PR DESCRIPTION
**Pull request by slachiewicz**
Java 11 is required at runtime for:
- aspectj 1.9.8+ https://github.com/eclipse/org.aspectj/blob/master/docs/dist/doc/README-199.html
- org.eclipse.jdt:ecj 3.27.0+
- com.google.errorprone:error_prone_core 2.9.0+

### CODE REVIEW

**Comment by slachiewicz** [comment]
This is to fix #237 where we upgraded Java for part of artefacts in patch versions.
My goal is to restore compatibility, release one version and then upgrade project to Java 11 in next minor version

**Comment by slachiewicz** [comment]
Sorry #247 from issues

**Comment by olamy** [comment]
there is a probably a workaround https://github.com/codehaus-plexus/plexus-compiler/issues/247#issuecomment-1503003416

**Comment by slachiewicz** [comment]
As I mentioned above. Goal is to release one that support Java 8 and then release next versions where we explicitly say that we support only Java 11. Difference in few days only.

**Comment by olamy** [comment]
> As I mentioned above. Goal is to release one that support Java 8 and then release next versions where we explicitly say that we support only Java 11. Difference in few days only.

-1 to this it doesn’t make sense because of the changes to the downstream dependencies (ecj, aspectj, errorprone).... 
again there is probably a workaround for this user to try...
if you want to do so. create a release branch 1.12.1.x and work on this with a release 1.12.1.1 (but frankly that's non sense) but do not downgrade master branch it doesn’t make sense....

**Comment by slachiewicz** [comment]
Thank you for you input.

**Pull request closed without merging**
