### PR TITLE
Issue #111 - Refactor and add unit tests for support for multiple --add-exp…

### PR DESCRIPTION
**Pull request by eilensm**
…orts custom compiler arguments

This is my first PR and I hope I got everything right so far...

### CODE REVIEW

**Review by tomaswolf — APPROVED** [review]
Looks good to me.

**Comment by tomaswolf** [comment]
@olamy could you take a look and merge if OK?

**Comment by tomaswolf** [comment]
Thank you!

**Comment by olamy** [comment]
no worries. really sorry for the delay

**Pull request merged**
