### PR TITLE
ecj and EclipseJavaCompiler update

### PR DESCRIPTION
**Pull request by tkirsch**
update ecj to latest version and make EclipseJavaCompiler recognize java 9

### CODE REVIEW

**Comment by olamy** [comment]
This means the build will now Java 8 mandatory.
PERSO I don't mind.
someone with complain? @rfscholte @hboutemy  ?

**Comment by rfscholte** [comment]
Building with Java8 while source/target on 1.7? Fine by me.

**Comment by olamy** [comment]
@tkirsch is it something you can add in you pr? change travis as well to build only with java8.

**Comment by tkirsch** [comment]
yes. will change javaVersion to 7 and remove the openjdk7 from travis.

**Comment by tkirsch** [comment]
don't know anything about animal sniffer but will have a look

**Comment by olamy** [comment]
Merged
Thanks @tkirsch !!

**Pull request merged**
