### PR TITLE
Miscellaneous linting & cleanups

### PR DESCRIPTION
**Pull request by rhowe**
I ran the IntelliJ IDEA linter in Java 7 mode and did some of the things it suggested.

Is this palatable?

### CODE REVIEW

**Comment by rhowe** [comment]
> PR has conflicts by now

Not too surprising after 2 years! I'm happy to remake it, if you're happy to review

**Comment by rfscholte** [comment]
I'm not surprised either. If you can provide a PR in a couple of hours, that would be great. I'd like to push a new release after that.

**Comment by rhowe** [comment]
> I'm not surprised either. If you can provide a PR in a couple of hours, that would be great. I'd like to push a new release after that.

I managed a few of the safer-looking ones at least. See what you think:

https://github.com/codehaus-plexus/plexus-compiler/pull/152

**Comment by rfscholte** [comment]
superseded by https://github.com/codehaus-plexus/plexus-compiler/pull/152

**Pull request closed without merging**
