### PR TITLE
If getting local repo from settings.xml, do it right

### PR DESCRIPTION
**Pull request by cstamas**
There are people who intentionally use non-default local repository locations, plus, they may have some expressions in the settings.xml...

So, if you do utilize code to get local repo from settings.xml, do it right. For me this whole stuff was not buildable due my (otherwise valid) settings.xml and non-default location of my local repository (that is on purpose not in default location).

### CODE REVIEW

**Comment by gnodet** [comment]
I would think the correct way to build settings is to use [`SettingsBuilder`](https://github.com/apache/maven/blob/master/maven-settings-builder/src/main/java/org/apache/maven/settings/building/SettingsBuilder.java).

Though this is only used during tests, so that should be fine...

**Comment by cstamas** [comment]
Ideally, I'd drop all the deprecated stuff from maven-artifact as well (ArtifactRepo, layout...) as ultimately the goal here is "just" to get a file from local repo... To make it "proper" using SettingsBuilder and maybe SimpleLocalRepositoryManager from resolver, that would need _all of maven and resolver_ (almost) just to perform this single thing...

Maybe the UT is wrong, and all we need is just to have this commons artifact under `src/test/resources` instead?

**Comment by kwin** [comment]
There is an easier solution in #357, please have a look.

**Comment by cstamas** [comment]
Did you try with settings.xml having `${env.XXX}` inside? :wink:

**Comment by slawekjaranowski** [comment]
IMHO tests are wrong, local repo is used to discover path for artifacts to build classpath ... 
We need to check if we can simply give any path for assertions

**Comment by kwin** [comment]
> Did you try with settings.xml having ${env.XXX} inside? 😉

Yes, because the `SettingsBuilder` does the interpolation (https://github.com/apache/maven/blob/42559937d8c4ed8a361422a8db3dfa6ef81fef21/maven-settings-builder/src/main/java/org/apache/maven/settings/building/DefaultSettingsBuilder.java#L235)

**Comment by slawekjaranowski** [comment]
suppressed by ##366 - now pass path to local repo from executing Maven

**Pull request closed without merging**
