### PR TITLE
Allow -log argument for Eclipse compiler - Issue #55

### PR DESCRIPTION
**Pull request by jftsunami**
Fix for issue #55

### CODE REVIEW

**Comment by michael-o** [comment]
Please clean up the commit mess.

**Comment by olamy** [comment]
@jftsunami please rebase as there are merge conflicts

**Comment by jftsunami** [comment]
@olamy  On it

**Comment by jftsunami** [comment]
@olamy That should do it.

**Comment by gnodet** [comment]
Superseded by #312

**Pull request closed without merging**
