### PR TITLE
Upgrade to eclipse compiler 3.11.0.v20150601-1755 from eclipse maven repository

### PR DESCRIPTION
**Pull request by guillaumecle**
Fix for issue #10

### CODE REVIEW

**Comment by mbaechler** [comment]
ecj 4.5 is on maven central for some times now, what about merge this PR ?

**Comment by guillaumecle** [comment]
I think we now would like to use
```xml
<dependency>
	<groupId>org.eclipse.tycho</groupId>
	<artifactId>org.eclipse.jdt.core</artifactId>
	<version>3.11.1.v20150902-1521</version>
</dependency>
```
instead of the one hosted on eclipse maven repository (that has disappeared since then).
I'll update the PR with that version.

**Comment by guillaumecle** [comment]
FYI, to get the latest jdt on my own project build I just override the dependency in my pom like that:
```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>3.5.1</version>
	[...]
	<dependencies>
		<dependency>
			<groupId>org.codehaus.plexus</groupId>
			<artifactId>plexus-compiler-eclipse</artifactId>
			<version>2.7</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.tycho</groupId>
			<artifactId>org.eclipse.jdt.core</artifactId>
			<version>3.11.1.v20150902-1521</version>
		</dependency>
	</dependencies>
</plugin>
```

**Comment by mbaechler** [comment]
I don't know eclipse modules well but how is org.eclipse.tycho related to 
```
<dependency>
    <groupId>org.eclipse.jdt.core.compiler</groupId>
    <artifactId>ecj</artifactId>
    <version>4.5.1</version>
</dependency>
```

The latest seems to share eclipse versioning, but what version is in use in eclipse ?

**Comment by guillaumecle** [comment]
I learned that `org.eclipse.jdt.core.compiler:ecj` was not published by eclipse itself but by a community member. I think there is no official release of ecj on maven central. Here the [eclipse ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=471373) about publishing it.
The `org.eclipse.tycho:org.eclipse.jdt.core` version on maven central is currently the most often updated.
Also eclipse maintains its own maven repo that is accessible [here](https://repo.eclipse.org/#view-repositories;eclipse~browsestorage) where you can find `org.eclipse.jdt:org.eclipse.jdt.core`

**Pull request merged**
